lazy_static! {
           static ref CONSTANTS_MAP: HashMap<&'static str, Vec<(String,String)>> = {
             let mut m = HashMap::new();m.insert("sensor_msgs__msg__Range", vec![("ULTRASOUND".to_string(), "_bindgen_ty_136".to_string()),("INFRARED".to_string(), "_bindgen_ty_137".to_string())]);
m.insert("test_msgs__msg__Constants", vec![("BOOL_CONST".to_string(), "bool".to_string()),("BYTE_CONST".to_string(), "_bindgen_ty_159".to_string()),("CHAR_CONST".to_string(), "_bindgen_ty_160".to_string()),("FLOAT32_CONST".to_string(), "f32".to_string()),("FLOAT64_CONST".to_string(), "f64".to_string()),("INT8_CONST".to_string(), "_bindgen_ty_161".to_string()),("UINT8_CONST".to_string(), "_bindgen_ty_162".to_string()),("INT16_CONST".to_string(), "_bindgen_ty_163".to_string()),("UINT16_CONST".to_string(), "_bindgen_ty_164".to_string()),("INT32_CONST".to_string(), "_bindgen_ty_165".to_string()),("UINT32_CONST".to_string(), "_bindgen_ty_166".to_string()),("INT64_CONST".to_string(), "_bindgen_ty_167".to_string()),("UINT64_CONST".to_string(), "_bindgen_ty_168".to_string())]);
m.insert("actionlib_msgs__msg__GoalStatus", vec![("PENDING".to_string(), "_bindgen_ty_12".to_string()),("ACTIVE".to_string(), "_bindgen_ty_13".to_string()),("PREEMPTED".to_string(), "_bindgen_ty_14".to_string()),("SUCCEEDED".to_string(), "_bindgen_ty_15".to_string()),("ABORTED".to_string(), "_bindgen_ty_16".to_string()),("REJECTED".to_string(), "_bindgen_ty_17".to_string()),("PREEMPTING".to_string(), "_bindgen_ty_18".to_string()),("RECALLING".to_string(), "_bindgen_ty_19".to_string()),("RECALLED".to_string(), "_bindgen_ty_20".to_string()),("LOST".to_string(), "_bindgen_ty_21".to_string())]);
m.insert("tf2_msgs__msg__TF2Error", vec![("NO_ERROR".to_string(), "_bindgen_ty_239".to_string()),("LOOKUP_ERROR".to_string(), "_bindgen_ty_240".to_string()),("CONNECTIVITY_ERROR".to_string(), "_bindgen_ty_241".to_string()),("EXTRAPOLATION_ERROR".to_string(), "_bindgen_ty_242".to_string()),("INVALID_ARGUMENT_ERROR".to_string(), "_bindgen_ty_243".to_string()),("TIMEOUT_ERROR".to_string(), "_bindgen_ty_244".to_string()),("TRANSFORM_ERROR".to_string(), "_bindgen_ty_245".to_string())]);
m.insert("action_msgs__srv__CancelGoal_Response", vec![("ERROR_NONE".to_string(), "_bindgen_ty_8".to_string()),("ERROR_REJECTED".to_string(), "_bindgen_ty_9".to_string()),("ERROR_UNKNOWN_GOAL_ID".to_string(), "_bindgen_ty_10".to_string()),("ERROR_GOAL_TERMINATED".to_string(), "_bindgen_ty_11".to_string())]);
m.insert("sensor_msgs__msg__NavSatFix", vec![("COVARIANCE_TYPE_UNKNOWN".to_string(), "_bindgen_ty_116".to_string()),("COVARIANCE_TYPE_APPROXIMATED".to_string(), "_bindgen_ty_117".to_string()),("COVARIANCE_TYPE_DIAGONAL_KNOWN".to_string(), "_bindgen_ty_118".to_string()),("COVARIANCE_TYPE_KNOWN".to_string(), "_bindgen_ty_119".to_string())]);
m.insert("shape_msgs__msg__SolidPrimitive", vec![("BOX".to_string(), "_bindgen_ty_138".to_string()),("SPHERE".to_string(), "_bindgen_ty_139".to_string()),("CYLINDER".to_string(), "_bindgen_ty_140".to_string()),("CONE".to_string(), "_bindgen_ty_141".to_string()),("PRISM".to_string(), "_bindgen_ty_142".to_string()),("BOX_X".to_string(), "_bindgen_ty_143".to_string()),("BOX_Y".to_string(), "_bindgen_ty_144".to_string()),("BOX_Z".to_string(), "_bindgen_ty_145".to_string()),("SPHERE_RADIUS".to_string(), "_bindgen_ty_146".to_string()),("CYLINDER_HEIGHT".to_string(), "_bindgen_ty_147".to_string()),("CYLINDER_RADIUS".to_string(), "_bindgen_ty_148".to_string()),("CONE_HEIGHT".to_string(), "_bindgen_ty_149".to_string()),("CONE_RADIUS".to_string(), "_bindgen_ty_150".to_string()),("PRISM_HEIGHT".to_string(), "_bindgen_ty_151".to_string())]);
m.insert("rcl_interfaces__srv__ListParameters_Request", vec![("DEPTH_RECURSIVE".to_string(), "_bindgen_ty_89".to_string())]);
m.insert("test_msgs__msg__Strings", vec![("STRING_CONST".to_string(), "&[u8; 13usize]".to_string())]);
m.insert("action_msgs__msg__GoalStatus", vec![("STATUS_UNKNOWN".to_string(), "_bindgen_ty_1".to_string()),("STATUS_ACCEPTED".to_string(), "_bindgen_ty_2".to_string()),("STATUS_EXECUTING".to_string(), "_bindgen_ty_3".to_string()),("STATUS_CANCELING".to_string(), "_bindgen_ty_4".to_string()),("STATUS_SUCCEEDED".to_string(), "_bindgen_ty_5".to_string()),("STATUS_CANCELED".to_string(), "_bindgen_ty_6".to_string()),("STATUS_ABORTED".to_string(), "_bindgen_ty_7".to_string())]);
m.insert("rcl_interfaces__msg__ParameterType", vec![("PARAMETER_NOT_SET".to_string(), "_bindgen_ty_79".to_string()),("PARAMETER_BOOL".to_string(), "_bindgen_ty_80".to_string()),("PARAMETER_INTEGER".to_string(), "_bindgen_ty_81".to_string()),("PARAMETER_DOUBLE".to_string(), "_bindgen_ty_82".to_string()),("PARAMETER_STRING".to_string(), "_bindgen_ty_83".to_string()),("PARAMETER_BYTE_ARRAY".to_string(), "_bindgen_ty_84".to_string()),("PARAMETER_BOOL_ARRAY".to_string(), "_bindgen_ty_85".to_string()),("PARAMETER_INTEGER_ARRAY".to_string(), "_bindgen_ty_86".to_string()),("PARAMETER_DOUBLE_ARRAY".to_string(), "_bindgen_ty_87".to_string()),("PARAMETER_STRING_ARRAY".to_string(), "_bindgen_ty_88".to_string())]);
m.insert("visualization_msgs__msg__ImageMarker", vec![("CIRCLE".to_string(), "_bindgen_ty_246".to_string()),("LINE_STRIP".to_string(), "_bindgen_ty_247".to_string()),("LINE_LIST".to_string(), "_bindgen_ty_248".to_string()),("POLYGON".to_string(), "_bindgen_ty_249".to_string()),("POINTS".to_string(), "_bindgen_ty_250".to_string()),("ADD".to_string(), "_bindgen_ty_251".to_string()),("REMOVE".to_string(), "_bindgen_ty_252".to_string())]);
m.insert("diagnostic_msgs__msg__DiagnosticStatus", vec![("OK".to_string(), "_bindgen_ty_22".to_string()),("WARN".to_string(), "_bindgen_ty_23".to_string()),("ERROR".to_string(), "_bindgen_ty_24".to_string()),("STALE".to_string(), "_bindgen_ty_25".to_string())]);
m.insert("lifecycle_msgs__msg__Transition", vec![("TRANSITION_CREATE".to_string(), "_bindgen_ty_37".to_string()),("TRANSITION_CONFIGURE".to_string(), "_bindgen_ty_38".to_string()),("TRANSITION_CLEANUP".to_string(), "_bindgen_ty_39".to_string()),("TRANSITION_ACTIVATE".to_string(), "_bindgen_ty_40".to_string()),("TRANSITION_DEACTIVATE".to_string(), "_bindgen_ty_41".to_string()),("TRANSITION_UNCONFIGURED_SHUTDOWN".to_string(), "_bindgen_ty_42".to_string()),("TRANSITION_INACTIVE_SHUTDOWN".to_string(), "_bindgen_ty_43".to_string()),("TRANSITION_ACTIVE_SHUTDOWN".to_string(), "_bindgen_ty_44".to_string()),("TRANSITION_DESTROY".to_string(), "_bindgen_ty_45".to_string()),("TRANSITION_ON_CONFIGURE_SUCCESS".to_string(), "_bindgen_ty_46".to_string()),("TRANSITION_ON_CONFIGURE_FAILURE".to_string(), "_bindgen_ty_47".to_string()),("TRANSITION_ON_CONFIGURE_ERROR".to_string(), "_bindgen_ty_48".to_string()),("TRANSITION_ON_CLEANUP_SUCCESS".to_string(), "_bindgen_ty_49".to_string()),("TRANSITION_ON_CLEANUP_FAILURE".to_string(), "_bindgen_ty_50".to_string()),("TRANSITION_ON_CLEANUP_ERROR".to_string(), "_bindgen_ty_51".to_string()),("TRANSITION_ON_ACTIVATE_SUCCESS".to_string(), "_bindgen_ty_52".to_string()),("TRANSITION_ON_ACTIVATE_FAILURE".to_string(), "_bindgen_ty_53".to_string()),("TRANSITION_ON_ACTIVATE_ERROR".to_string(), "_bindgen_ty_54".to_string()),("TRANSITION_ON_DEACTIVATE_SUCCESS".to_string(), "_bindgen_ty_55".to_string()),("TRANSITION_ON_DEACTIVATE_FAILURE".to_string(), "_bindgen_ty_56".to_string()),("TRANSITION_ON_DEACTIVATE_ERROR".to_string(), "_bindgen_ty_57".to_string()),("TRANSITION_ON_SHUTDOWN_SUCCESS".to_string(), "_bindgen_ty_58".to_string()),("TRANSITION_ON_SHUTDOWN_FAILURE".to_string(), "_bindgen_ty_59".to_string()),("TRANSITION_ON_SHUTDOWN_ERROR".to_string(), "_bindgen_ty_60".to_string()),("TRANSITION_ON_ERROR_SUCCESS".to_string(), "_bindgen_ty_61".to_string()),("TRANSITION_ON_ERROR_FAILURE".to_string(), "_bindgen_ty_62".to_string()),("TRANSITION_ON_ERROR_ERROR".to_string(), "_bindgen_ty_63".to_string()),("TRANSITION_CALLBACK_SUCCESS".to_string(), "_bindgen_ty_64".to_string()),("TRANSITION_CALLBACK_FAILURE".to_string(), "_bindgen_ty_65".to_string()),("TRANSITION_CALLBACK_ERROR".to_string(), "_bindgen_ty_66".to_string())]);
m.insert("sensor_msgs__msg__BatteryState", vec![("POWER_SUPPLY_STATUS_UNKNOWN".to_string(), "_bindgen_ty_92".to_string()),("POWER_SUPPLY_STATUS_CHARGING".to_string(), "_bindgen_ty_93".to_string()),("POWER_SUPPLY_STATUS_DISCHARGING".to_string(), "_bindgen_ty_94".to_string()),("POWER_SUPPLY_STATUS_NOT_CHARGING".to_string(), "_bindgen_ty_95".to_string()),("POWER_SUPPLY_STATUS_FULL".to_string(), "_bindgen_ty_96".to_string()),("POWER_SUPPLY_HEALTH_UNKNOWN".to_string(), "_bindgen_ty_97".to_string()),("POWER_SUPPLY_HEALTH_GOOD".to_string(), "_bindgen_ty_98".to_string()),("POWER_SUPPLY_HEALTH_OVERHEAT".to_string(), "_bindgen_ty_99".to_string()),("POWER_SUPPLY_HEALTH_DEAD".to_string(), "_bindgen_ty_100".to_string()),("POWER_SUPPLY_HEALTH_OVERVOLTAGE".to_string(), "_bindgen_ty_101".to_string()),("POWER_SUPPLY_HEALTH_UNSPEC_FAILURE".to_string(), "_bindgen_ty_102".to_string()),("POWER_SUPPLY_HEALTH_COLD".to_string(), "_bindgen_ty_103".to_string()),("POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE".to_string(), "_bindgen_ty_104".to_string()),("POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE".to_string(), "_bindgen_ty_105".to_string()),("POWER_SUPPLY_TECHNOLOGY_UNKNOWN".to_string(), "_bindgen_ty_106".to_string()),("POWER_SUPPLY_TECHNOLOGY_NIMH".to_string(), "_bindgen_ty_107".to_string()),("POWER_SUPPLY_TECHNOLOGY_LION".to_string(), "_bindgen_ty_108".to_string()),("POWER_SUPPLY_TECHNOLOGY_LIPO".to_string(), "_bindgen_ty_109".to_string()),("POWER_SUPPLY_TECHNOLOGY_LIFE".to_string(), "_bindgen_ty_110".to_string()),("POWER_SUPPLY_TECHNOLOGY_NICD".to_string(), "_bindgen_ty_111".to_string()),("POWER_SUPPLY_TECHNOLOGY_LIMN".to_string(), "_bindgen_ty_112".to_string())]);
m.insert("visualization_msgs__msg__InteractiveMarkerUpdate", vec![("KEEP_ALIVE".to_string(), "_bindgen_ty_291".to_string()),("UPDATE".to_string(), "_bindgen_ty_292".to_string())]);
m.insert("visualization_msgs__msg__MenuEntry", vec![("FEEDBACK".to_string(), "_bindgen_ty_253".to_string()),("ROSRUN".to_string(), "_bindgen_ty_254".to_string()),("ROSLAUNCH".to_string(), "_bindgen_ty_255".to_string())]);
m.insert("visualization_msgs__msg__InteractiveMarkerControl", vec![("INHERIT".to_string(), "_bindgen_ty_256".to_string()),("FIXED".to_string(), "_bindgen_ty_257".to_string()),("VIEW_FACING".to_string(), "_bindgen_ty_258".to_string()),("NONE".to_string(), "_bindgen_ty_259".to_string()),("MENU".to_string(), "_bindgen_ty_260".to_string()),("BUTTON".to_string(), "_bindgen_ty_261".to_string()),("MOVE_AXIS".to_string(), "_bindgen_ty_262".to_string()),("MOVE_PLANE".to_string(), "_bindgen_ty_263".to_string()),("ROTATE_AXIS".to_string(), "_bindgen_ty_264".to_string()),("MOVE_ROTATE".to_string(), "_bindgen_ty_265".to_string()),("MOVE_3D".to_string(), "_bindgen_ty_266".to_string()),("ROTATE_3D".to_string(), "_bindgen_ty_267".to_string()),("MOVE_ROTATE_3D".to_string(), "_bindgen_ty_268".to_string())]);
m.insert("lifecycle_msgs__msg__State", vec![("PRIMARY_STATE_UNKNOWN".to_string(), "_bindgen_ty_26".to_string()),("PRIMARY_STATE_UNCONFIGURED".to_string(), "_bindgen_ty_27".to_string()),("PRIMARY_STATE_INACTIVE".to_string(), "_bindgen_ty_28".to_string()),("PRIMARY_STATE_ACTIVE".to_string(), "_bindgen_ty_29".to_string()),("PRIMARY_STATE_FINALIZED".to_string(), "_bindgen_ty_30".to_string()),("TRANSITION_STATE_CONFIGURING".to_string(), "_bindgen_ty_31".to_string()),("TRANSITION_STATE_CLEANINGUP".to_string(), "_bindgen_ty_32".to_string()),("TRANSITION_STATE_SHUTTINGDOWN".to_string(), "_bindgen_ty_33".to_string()),("TRANSITION_STATE_ACTIVATING".to_string(), "_bindgen_ty_34".to_string()),("TRANSITION_STATE_DEACTIVATING".to_string(), "_bindgen_ty_35".to_string()),("TRANSITION_STATE_ERRORPROCESSING".to_string(), "_bindgen_ty_36".to_string())]);
m.insert("rcl_interfaces__msg__Log", vec![("DEBUG".to_string(), "_bindgen_ty_72".to_string()),("INFO".to_string(), "_bindgen_ty_73".to_string()),("WARN".to_string(), "_bindgen_ty_74".to_string()),("ERROR".to_string(), "_bindgen_ty_75".to_string()),("FATAL".to_string(), "_bindgen_ty_76".to_string())]);
m.insert("visualization_msgs__msg__InteractiveMarkerFeedback", vec![("KEEP_ALIVE".to_string(), "_bindgen_ty_285".to_string()),("POSE_UPDATE".to_string(), "_bindgen_ty_286".to_string()),("MENU_SELECT".to_string(), "_bindgen_ty_287".to_string()),("BUTTON_CLICK".to_string(), "_bindgen_ty_288".to_string()),("MOUSE_DOWN".to_string(), "_bindgen_ty_289".to_string()),("MOUSE_UP".to_string(), "_bindgen_ty_290".to_string())]);
m.insert("sensor_msgs__msg__PointField", vec![("INT8".to_string(), "_bindgen_ty_128".to_string()),("UINT8".to_string(), "_bindgen_ty_129".to_string()),("INT16".to_string(), "_bindgen_ty_130".to_string()),("UINT16".to_string(), "_bindgen_ty_131".to_string()),("INT32".to_string(), "_bindgen_ty_132".to_string()),("UINT32".to_string(), "_bindgen_ty_133".to_string()),("FLOAT32".to_string(), "_bindgen_ty_134".to_string()),("FLOAT64".to_string(), "_bindgen_ty_135".to_string())]);
m.insert("sensor_msgs__msg__NavSatStatus", vec![("STATUS_NO_FIX".to_string(), "_bindgen_ty_120".to_string()),("STATUS_FIX".to_string(), "_bindgen_ty_121".to_string()),("STATUS_SBAS_FIX".to_string(), "_bindgen_ty_122".to_string()),("STATUS_GBAS_FIX".to_string(), "_bindgen_ty_123".to_string()),("SERVICE_GPS".to_string(), "_bindgen_ty_124".to_string()),("SERVICE_GLONASS".to_string(), "_bindgen_ty_125".to_string()),("SERVICE_COMPASS".to_string(), "_bindgen_ty_126".to_string()),("SERVICE_GALILEO".to_string(), "_bindgen_ty_127".to_string())]);
m.insert("nav_msgs__srv__LoadMap_Response", vec![("RESULT_SUCCESS".to_string(), "_bindgen_ty_67".to_string()),("RESULT_MAP_DOES_NOT_EXIST".to_string(), "_bindgen_ty_68".to_string()),("RESULT_INVALID_MAP_DATA".to_string(), "_bindgen_ty_69".to_string()),("RESULT_INVALID_MAP_METADATA".to_string(), "_bindgen_ty_70".to_string()),("RESULT_UNDEFINED_FAILURE".to_string(), "_bindgen_ty_71".to_string())]);
m.insert("sensor_msgs__msg__JoyFeedback", vec![("TYPE_LED".to_string(), "_bindgen_ty_113".to_string()),("TYPE_RUMBLE".to_string(), "_bindgen_ty_114".to_string()),("TYPE_BUZZER".to_string(), "_bindgen_ty_115".to_string())]);
m.insert("statistics_msgs__msg__StatisticDataType", vec![("STATISTICS_DATA_TYPE_UNINITIALIZED".to_string(), "_bindgen_ty_153".to_string()),("STATISTICS_DATA_TYPE_AVERAGE".to_string(), "_bindgen_ty_154".to_string()),("STATISTICS_DATA_TYPE_MINIMUM".to_string(), "_bindgen_ty_155".to_string()),("STATISTICS_DATA_TYPE_MAXIMUM".to_string(), "_bindgen_ty_156".to_string()),("STATISTICS_DATA_TYPE_STDDEV".to_string(), "_bindgen_ty_157".to_string()),("STATISTICS_DATA_TYPE_SAMPLE_COUNT".to_string(), "_bindgen_ty_158".to_string())]);
m.insert("visualization_msgs__msg__Marker", vec![("ARROW".to_string(), "_bindgen_ty_269".to_string()),("CUBE".to_string(), "_bindgen_ty_270".to_string()),("SPHERE".to_string(), "_bindgen_ty_271".to_string()),("CYLINDER".to_string(), "_bindgen_ty_272".to_string()),("LINE_STRIP".to_string(), "_bindgen_ty_273".to_string()),("LINE_LIST".to_string(), "_bindgen_ty_274".to_string()),("CUBE_LIST".to_string(), "_bindgen_ty_275".to_string()),("SPHERE_LIST".to_string(), "_bindgen_ty_276".to_string()),("POINTS".to_string(), "_bindgen_ty_277".to_string()),("TEXT_VIEW_FACING".to_string(), "_bindgen_ty_278".to_string()),("MESH_RESOURCE".to_string(), "_bindgen_ty_279".to_string()),("TRIANGLE_LIST".to_string(), "_bindgen_ty_280".to_string()),("ADD".to_string(), "_bindgen_ty_281".to_string()),("MODIFY".to_string(), "_bindgen_ty_282".to_string()),("DELETE".to_string(), "_bindgen_ty_283".to_string()),("DELETEALL".to_string(), "_bindgen_ty_284".to_string())]);
m 
 }; }

