pub mod radar_msgs{include!(concat!(env!("OUT_DIR"), "/radar_msgs.rs"));}
pub mod rosgraph_msgs{include!(concat!(env!("OUT_DIR"), "/rosgraph_msgs.rs"));}
pub mod composition_interfaces{include!(concat!(env!("OUT_DIR"), "/composition_interfaces.rs"));}
pub mod map_msgs{include!(concat!(env!("OUT_DIR"), "/map_msgs.rs"));}
pub mod rosbridge_msgs{include!(concat!(env!("OUT_DIR"), "/rosbridge_msgs.rs"));}
pub mod topic_tools_interfaces{include!(concat!(env!("OUT_DIR"), "/topic_tools_interfaces.rs"));}
pub mod trajectory_msgs{include!(concat!(env!("OUT_DIR"), "/trajectory_msgs.rs"));}
pub mod visualization_msgs{include!(concat!(env!("OUT_DIR"), "/visualization_msgs.rs"));}
pub mod rosbag2_interfaces{include!(concat!(env!("OUT_DIR"), "/rosbag2_interfaces.rs"));}
pub mod geographic_msgs{include!(concat!(env!("OUT_DIR"), "/geographic_msgs.rs"));}
pub mod nav_msgs{include!(concat!(env!("OUT_DIR"), "/nav_msgs.rs"));}
pub mod shape_msgs{include!(concat!(env!("OUT_DIR"), "/shape_msgs.rs"));}
pub mod action_tutorials_interfaces{include!(concat!(env!("OUT_DIR"), "/action_tutorials_interfaces.rs"));}
pub mod can_msgs{include!(concat!(env!("OUT_DIR"), "/can_msgs.rs"));}
pub mod pendulum_msgs{include!(concat!(env!("OUT_DIR"), "/pendulum_msgs.rs"));}
pub mod geometry_msgs{include!(concat!(env!("OUT_DIR"), "/geometry_msgs.rs"));}
pub mod turtlesim{include!(concat!(env!("OUT_DIR"), "/turtlesim.rs"));}
pub mod builtin_interfaces{include!(concat!(env!("OUT_DIR"), "/builtin_interfaces.rs"));}
pub mod nav2_msgs{include!(concat!(env!("OUT_DIR"), "/nav2_msgs.rs"));}
pub mod statistics_msgs{include!(concat!(env!("OUT_DIR"), "/statistics_msgs.rs"));}
pub mod octomap_msgs{include!(concat!(env!("OUT_DIR"), "/octomap_msgs.rs"));}
pub mod sensor_msgs{include!(concat!(env!("OUT_DIR"), "/sensor_msgs.rs"));}
pub mod action_msgs{include!(concat!(env!("OUT_DIR"), "/action_msgs.rs"));}
pub mod actionlib_msgs{include!(concat!(env!("OUT_DIR"), "/actionlib_msgs.rs"));}
pub mod logging_demo{include!(concat!(env!("OUT_DIR"), "/logging_demo.rs"));}
pub mod diagnostic_msgs{include!(concat!(env!("OUT_DIR"), "/diagnostic_msgs.rs"));}
pub mod pcl_msgs{include!(concat!(env!("OUT_DIR"), "/pcl_msgs.rs"));}
pub mod rmw_dds_common{include!(concat!(env!("OUT_DIR"), "/rmw_dds_common.rs"));}
pub mod stereo_msgs{include!(concat!(env!("OUT_DIR"), "/stereo_msgs.rs"));}
pub mod theora_image_transport{include!(concat!(env!("OUT_DIR"), "/theora_image_transport.rs"));}
pub mod ublox_msgs{include!(concat!(env!("OUT_DIR"), "/ublox_msgs.rs"));}
pub mod lifecycle_msgs{include!(concat!(env!("OUT_DIR"), "/lifecycle_msgs.rs"));}
pub mod std_srvs{include!(concat!(env!("OUT_DIR"), "/std_srvs.rs"));}
pub mod example_interfaces{include!(concat!(env!("OUT_DIR"), "/example_interfaces.rs"));}
pub mod rosapi_msgs{include!(concat!(env!("OUT_DIR"), "/rosapi_msgs.rs"));}
pub mod rcl_interfaces{include!(concat!(env!("OUT_DIR"), "/rcl_interfaces.rs"));}
pub mod tf2_msgs{include!(concat!(env!("OUT_DIR"), "/tf2_msgs.rs"));}
pub mod unique_identifier_msgs{include!(concat!(env!("OUT_DIR"), "/unique_identifier_msgs.rs"));}
pub mod pacmod3_msgs{include!(concat!(env!("OUT_DIR"), "/pacmod3_msgs.rs"));}
pub mod bond{include!(concat!(env!("OUT_DIR"), "/bond.rs"));}
pub mod std_msgs{include!(concat!(env!("OUT_DIR"), "/std_msgs.rs"));}
