[package]
name = "rcl"
version = "0.0.2"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0.4"
widestring = "0.4.3"

[build-dependencies]
bindgen = "0.57.0"
